package com.rescuefarm.service;
import com.rescuefarm.domain.enums.*;import com.rescuefarm.domain.model.*;import com.rescuefarm.service.seller.*;import java.util.*;import org.junit.Test;import static org.junit.Assert.*;
public class SellerDashboardAggregatorTest{
 private final SellerDashboardAggregator aggregator=new SellerDashboardAggregator();
 @Test public void filtersEveryResourceBySellerOwnership(){SellerDashboardSnapshot x=aggregator.aggregate("s1",Arrays.asList(product("p1","s1"),product("p2","s2")),Arrays.asList(campaign("c1","s1"),campaign("c2","s2")),Arrays.asList(post("x1","s1"),post("x2","s2")),Arrays.asList(order("o1","s1",OrderStatus.PENDING,FulfillmentType.PICKUP,100),order("o2","s2",OrderStatus.DELIVERED,FulfillmentType.DELIVERY,900)),2);assertEquals(1,x.getProducts());assertEquals(1,x.getCampaigns());assertEquals(1,x.getPosts());assertEquals(1,x.getOrders());assertEquals(0,x.getRevenue(),0.001);}
 @Test public void dashboardCountsRevenueOnlyAfterDelivered(){SellerDashboardSnapshot x=aggregator.aggregate("s",Collections.emptyList(),Collections.emptyList(),Collections.emptyList(),Arrays.asList(order("a","s",OrderStatus.DELIVERED,FulfillmentType.DELIVERY,120),order("b","s",OrderStatus.PENDING,FulfillmentType.PICKUP,80)),0);assertEquals(120,x.getRevenue(),0.001);assertEquals(1,x.getPendingOrders());assertEquals(1,x.getDeliveryOrders());}
 @Test public void recentOrdersAreCappedForDashboardPagination(){List<Order>orders=new ArrayList<>();for(int i=0;i<7;i++)orders.add(order("o"+i,"s",OrderStatus.PENDING,FulfillmentType.PICKUP,1));SellerDashboardSnapshot x=aggregator.aggregate("s",null,null,null,orders,0);assertEquals(5,x.getRecentOrders().size());assertTrue(x.hasMoreOrders());}
 @Test public void routesMapNestedManagementToOwningScreen(){SellerRoutePolicy p=new SellerRoutePolicy();assertEquals(SellerRoutePolicy.Destination.PRODUCTS,p.destinationFor("batches"));assertEquals(SellerRoutePolicy.Destination.PRODUCTS,p.destinationFor("promotions"));assertEquals(SellerRoutePolicy.Destination.CAMPAIGNS,p.destinationFor("mobile"));assertEquals(SellerRoutePolicy.Destination.ORDERS,p.destinationFor("shipments"));}
 private Product product(String id,String seller){return Product.restore(id,seller,"cat","Rau","Mô tả",100,80,"kg","VN","HN",Collections.emptyList(),0,0,ProductStatus.ACTIVE);}private Post post(String id,String seller){return Post.restore(id,seller,"","Bài viết","Nội dung đủ dài",Collections.emptyList(),Collections.emptyList(),UrgencyLevel.NORMAL,PostStatus.PENDING_APPROVAL,0,new Date());}
 private RescueCampaign campaign(String id,String seller){Map<String,Double>targets=new HashMap<>();targets.put("b",10D);return RescueCampaign.restore(id,seller,"Giải cứu","",RescueReason.OVER_SUPPLY,UrgencyLevel.NORMAL,RescueMode.FIXED_POINT,targets,10,0,2,new Date(1),new Date(System.currentTimeMillis()+100000),0,0,0,0,null,false,"HN",CampaignStatus.ACTIVE);}
 private Order order(String id,String seller,OrderStatus status,FulfillmentType type,double total){return Order.restore(id,OrderOwnerType.CUSTOMER,"u","RF-"+id,seller,"",type,"Người nhận","0900000000","HN",0,0,total,0,0,total,PaymentMethod.BANK_TRANSFER,status==OrderStatus.DELIVERED?PaymentStatus.PAID:PaymentStatus.PENDING,status,"",new Date(),new Date(),Collections.emptyList());}
}
