package com.rescuefarm.ui.order;

import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.fragment.app.Fragment;import androidx.lifecycle.ViewModelProvider;import com.google.firebase.auth.FirebaseAuth;import com.rescuefarm.R;import com.rescuefarm.domain.enums.*;import com.rescuefarm.domain.model.*;import java.text.NumberFormat;import java.util.Locale;

public class OrderDetailFragment extends Fragment {
    private OrderViewModel vm;private TextView detail,instructions,message;private Spinner target;private EditText reference;private View transitionButton,confirmButton;private String orderId="";
    @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup p,@Nullable Bundle s){return i.inflate(R.layout.fragment_order_detail,p,false);}
    @Override public void onViewCreated(@NonNull View v,@Nullable Bundle s){detail=v.findViewById(R.id.orderDetailText);instructions=v.findViewById(R.id.paymentInstructionsText);message=v.findViewById(R.id.orderLifecycleMessage);target=v.findViewById(R.id.orderStatusTarget);reference=v.findViewById(R.id.bankReferenceInput);transitionButton=v.findViewById(R.id.transitionOrderButton);confirmButton=v.findViewById(R.id.confirmBankTransferButton);target.setAdapter(new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_dropdown_item,OrderStatus.values()));Bundle a=getArguments();orderId=a==null?"":a.getString("orderId","");vm=new ViewModelProvider(this,new OrderViewModelFactory(requireContext())).get(OrderViewModel.class);vm.getState().observe(getViewLifecycleOwner(),this::render);transitionButton.setOnClickListener(x->vm.transition(orderId,(OrderStatus)target.getSelectedItem()));confirmButton.setOnClickListener(x->vm.confirmTransfer(orderId,reference.getText().toString().trim()));if(orderId.isEmpty())message.setText(R.string.order_id_missing);else vm.load(orderId);}
    private void render(OrderLifecycleState state){message.setText(state.getMessage());boolean loading=state.getStatus()==OrderLifecycleState.Status.LOADING;transitionButton.setEnabled(!loading);confirmButton.setEnabled(!loading);if(state.getStatus()==OrderLifecycleState.Status.ERROR){Toast.makeText(requireContext(),state.getMessage(),Toast.LENGTH_LONG).show();return;}if(state.getStatus()!=OrderLifecycleState.Status.SUCCESS)return;Order o=state.getOrder();Payment p=state.getPayment();Shipment sh=state.getShipment();String shipment=sh==null?getString(R.string.shipment_not_required):sh.getStatus().name();detail.setText(getString(R.string.order_detail_format,o.getOrderCode(),o.getStatus().name(),o.getFulfillmentType().name(),p.getMethod().name(),p.getStatus().name(),shipment,NumberFormat.getCurrencyInstance(new Locale("vi","VN")).format(o.getTotalAmount())));instructions.setText(paymentInstructions(p));String uid=FirebaseAuth.getInstance().getCurrentUser()==null?"":FirebaseAuth.getInstance().getCurrentUser().getUid();boolean seller=uid.equals(o.getSellerId());transitionButton.setVisibility(seller?View.VISIBLE:View.GONE);target.setVisibility(seller?View.VISIBLE:View.GONE);boolean bank=seller&&p.getMethod()==PaymentMethod.BANK_TRANSFER&&p.getStatus()==PaymentStatus.PENDING;reference.setVisibility(bank?View.VISIBLE:View.GONE);confirmButton.setVisibility(bank?View.VISIBLE:View.GONE);}
    private String paymentInstructions(Payment p){if(p.getMethod()==PaymentMethod.BANK_TRANSFER)return getString(R.string.bank_transfer_manual_instruction,p.getOrderId());if(p.getMethod()==PaymentMethod.CASH_ON_SITE)return getString(R.string.cash_onsite_instruction);return getString(R.string.cod_instruction);}
}
