package com.rescuefarm.service.notification;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.Build;import androidx.core.app.NotificationCompat;import com.google.firebase.auth.FirebaseAuth;import com.google.firebase.messaging.*;import com.rescuefarm.MainActivity;import com.rescuefarm.R;import com.rescuefarm.data.repository.*;import com.rescuefarm.domain.enums.NotificationType;import com.rescuefarm.service.engagement.NotificationDeepLinkService;import java.util.Map;
public class RescueFarmMessagingService extends FirebaseMessagingService{
 private static final String CHANNEL_ID="rescuefarm_updates";
 @Override public void onNewToken(String token){String uid=FirebaseAuth.getInstance().getCurrentUser()==null?"":FirebaseAuth.getInstance().getCurrentUser().getUid();if(uid.isEmpty())return;EngagementRepositoryFactory.create(this).registerFcmToken(uid,token,new EngagementRepository.ActionCallback(){public void onSuccess(){}public void onError(EngagementRepository.ErrorCode c,String m){}});}
 @Override public void onMessageReceived(RemoteMessage message){Map<String,String>d=message.getData();RemoteMessage.Notification n=message.getNotification();String title=n==null?d.get("title"):n.getTitle(),body=n==null?d.get("body"):n.getBody();NotificationType type=parse(d.get("type"));String reference=d.get("referenceId");String link=new NotificationDeepLinkService().build(type,reference);createChannel();Intent intent=new Intent(Intent.ACTION_VIEW, Uri.parse(link),this, MainActivity.class);intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent pending=PendingIntent.getActivity(this,Math.abs((link+System.currentTimeMillis()).hashCode()),intent,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);android.app.Notification notification=new NotificationCompat.Builder(this,CHANNEL_ID).setSmallIcon(R.mipmap.ic_launcher).setContentTitle(title==null?getString(R.string.app_name):title).setContentText(body==null?"":body).setAutoCancel(true).setContentIntent(pending).setPriority(NotificationCompat.PRIORITY_HIGH).build();NotificationManager manager=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);manager.notify(Math.abs(message.getMessageId()==null?link.hashCode():message.getMessageId().hashCode()),notification);}
 private void createChannel(){if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O){NotificationChannel c=new NotificationChannel(CHANNEL_ID,getString(R.string.notification_channel_name),NotificationManager.IMPORTANCE_HIGH);c.setDescription(getString(R.string.notification_channel_description));((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}}
 private NotificationType parse(String v){try{return NotificationType.valueOf(v==null?"SYSTEM":v);}catch(Exception e){return NotificationType.SYSTEM;}}
}
